### ISSUE TITLE
filter values not working for Mongoid.

### ISSUE THREAD

**Issue by dennisfaust** [JSONAPI-Resources/jsonapi-resources#177] opened 2015-04-27 20:50 UTC
We are trying to retrieve documents from Mongo using the filters business_id and person_id. With the filter values like this:

http://localhost:3000/api/v1/emails?filter[business_id]=123

Those are then each being converted to an array by CVS.parse_line in `Resource#verify_keys` like so:

``` ruby
'business_id' => ['123']
```

ActiveRecord will convert `where(business_id: ['123'])` to an `in` clause which is effectively an OR operation.  Mongoid (and Mongo), however, will use the array as the value (since Mongo supports arrays as fields).  This does not have the same semantics as an `in` clause in AR.  As a result, our filters return no results because obviously we are not storing the business_id as an array. 

We looked at tweaking this behavior in the `verify_filter` method but quickly realized that method is used for other purposes.  Many tests broke after we applied the following:

``` ruby
      def verify_filter(filter, raw, context = nil)
        filter_values = case raw
        when String
          parts = CSV.parse_line(raw)
          parts.length > 1 ? parts : raw
        else
          raw
        end

        if is_filter_association?(filter)
          verify_association_filter(filter, filter_values, context)
        else
          verify_custom_filter(filter, filter_values, context)
        end
      end
```

We'd love to help out with a patch but could use some guidance on how you think this should be handled.

**Comment by bvandenbos** [comment] 2015-04-27 21:14
Dup of https://github.com/cerebris/jsonapi-resources/issues/118

**Comment by dennisfaust** [comment] 2015-04-28 16:15
Here's a hack we're using if you run into this:

```
  def self.apply_filter(records, filter, value)
    if value.is_a?(Array)
      raise "Not Supported: value contains >1 element: #{value}" if value.length > 1
      value = value.first
    end
    records.where(filter => value)
  end
```

Obviously, this doesn't work if the filter does contain an array of elements.

**Comment by juanibiapina** [comment] 2016-09-20 20:57
Updates on this?

**Comment by tommy-russoniello** [comment] 2020-10-28 02:37
Duplicate of #118

**Closed as completed by tommy-russoniello** 2020-10-28 02:37 UTC
