### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Keqi** [JSONAPI-Resources/jsonapi-resources#731] opened 2016-06-07 10:55 UTC
Is there any way to cache responses/resources the Rails way? I don't see anything in docs.

**Comment by lgebhardt** [comment] 2016-06-07 19:48
Not yet. #712 does some caching and it does improve the performance noticeably. I'm hoping we can get it merged soon.

**Comment by DavidMikeSimon** [comment] 2016-08-01 17:16
@Keqi try the current master now, see the README documentaion regarding "resource caching".

**Comment by johnmosesman** [comment] 2016-08-13 16:37
@DavidMikeSimon Just a thought, but I recently tried to use the caching behavior described in the [README](https://github.com/cerebris/jsonapi-resources), and I get:

```
undefined method `resource_cache=' for #<JSONAPI::Configuration:0x007f917396d208>`
```

unless I point my gemfile towards the github URL. None of the gems on Rubygems (`0.7.0 - 0.8.0.beta2`) have the config item.

The way its presented in the README makes me think it should be in there. Might be worth putting a message in the README about this?

**Comment by lgebhardt** [comment] 2016-08-14 02:59
The problem is the readme displayed is for the master branch, but this feature hasn't been released yet. The plan is to release 0.8.0 this coming week and then caching will go in a 0.9.0.beta1 release along with a few other changes. We need a different solution for release documentation as the current way is obviously confusing.

**Comment by sardaukar** [comment] 2018-06-13 13:08
@lgebhardt is this still being worked on?

Nevermind, just noticed 0.9.0 is out already!

**Closed as completed** 2020-10-27 22:53 UTC
